// Mocks generated by Mockito 5.4.4 from annotations
// in elada/test/presentation/screens/invoice_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i6;

import 'package:elada/presentation/providers/invoice_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [InvoiceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceProvider extends _i1.Mock implements _i2.InvoiceProvider {
  MockInvoiceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  double get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0.0,
      ) as double);

  @override
  String get invoiceNumber => (super.noSuchMethod(
        Invocation.getter(#invoiceNumber),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#invoiceNumber),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateDescription(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateDescription,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTotal(double? value) => super.noSuchMethod(
        Invocation.method(
          #updateTotal,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateInvoiceNumber(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateInvoiceNumber,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void incrementInvoiceNumber() => super.noSuchMethod(
        Invocation.method(
          #incrementInvoiceNumber,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.Uint8List> generateInvoice(_i5.Uint8List? templateBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInvoice,
          [templateBytes],
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
