// Mocks generated by Mockito 5.4.4 from annotations
// in elada/test/presentation/providers/invoice_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:elada/data/models/invoice.dart' as _i4;
import 'package:elada/data/repositories/invoice_repository.dart' as _i2;
import 'package:elada/domain/services/pdf_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [InvoiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceRepository extends _i1.Mock implements _i2.InvoiceRepository {
  MockInvoiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveInvoice(_i4.Invoice? invoice) => (super.noSuchMethod(
        Invocation.method(
          #saveInvoice,
          [invoice],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.Invoice> getInvoices() => (super.noSuchMethod(
        Invocation.method(
          #getInvoices,
          [],
        ),
        returnValue: <_i4.Invoice>[],
      ) as List<_i4.Invoice>);

  @override
  String getLastInvoiceNumber() => (super.noSuchMethod(
        Invocation.method(
          #getLastInvoiceNumber,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getLastInvoiceNumber,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<void> saveLastInvoiceNumber(String? number) => (super.noSuchMethod(
        Invocation.method(
          #saveLastInvoiceNumber,
          [number],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfService extends _i1.Mock implements _i6.PdfService {
  MockPdfService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.Uint8List> generateInvoice({
    required String? description,
    required double? total,
    required String? invoiceNumber,
    required _i7.Uint8List? templateBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInvoice,
          [],
          {
            #description: description,
            #total: total,
            #invoiceNumber: invoiceNumber,
            #templateBytes: templateBytes,
          },
        ),
        returnValue: _i3.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i3.Future<_i7.Uint8List>);
}
