// Mocks generated by Mockito 5.4.4 from annotations
// in elada/test/presentation/widgets/invoice_preview_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i4;
import 'dart:ui' as _i9;

import 'package:elada/data/models/invoice.dart' as _i7;
import 'package:elada/data/models/invoice_item.dart' as _i6;
import 'package:elada/presentation/providers/invoice_provider.dart' as _i3;
import 'package:flutter/foundation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InvoiceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceProvider extends _i1.Mock implements _i3.InvoiceProvider {
  MockInvoiceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<_i4.Uint8List?> get previewBytesNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#previewBytesNotifier),
        returnValue: _FakeValueNotifier_0<_i4.Uint8List?>(
          this,
          Invocation.getter(#previewBytesNotifier),
        ),
      ) as _i2.ValueNotifier<_i4.Uint8List?>);

  @override
  _i2.ValueNotifier<bool> get isPreviewLoadingNotifier => (super.noSuchMethod(
        Invocation.getter(#isPreviewLoadingNotifier),
        returnValue: _FakeValueNotifier_0<bool>(
          this,
          Invocation.getter(#isPreviewLoadingNotifier),
        ),
      ) as _i2.ValueNotifier<bool>);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  double get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasItems => (super.noSuchMethod(
        Invocation.getter(#hasItems),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.InvoiceItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i6.InvoiceItem>[],
      ) as List<_i6.InvoiceItem>);

  @override
  String get invoiceNumber => (super.noSuchMethod(
        Invocation.getter(#invoiceNumber),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#invoiceNumber),
        ),
      ) as String);

  @override
  DateTime get date => (super.noSuchMethod(
        Invocation.getter(#date),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#date),
        ),
      ) as DateTime);

  @override
  String get selectedCurrency => (super.noSuchMethod(
        Invocation.getter(#selectedCurrency),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedCurrency),
        ),
      ) as String);

  @override
  List<_i7.Invoice> get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: <_i7.Invoice>[],
      ) as List<_i7.Invoice>);

  @override
  List<_i7.Invoice> get drafts => (super.noSuchMethod(
        Invocation.getter(#drafts),
        returnValue: <_i7.Invoice>[],
      ) as List<_i7.Invoice>);

  @override
  bool get isPreviewLoading => (super.noSuchMethod(
        Invocation.getter(#isPreviewLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isGenerating => (super.noSuchMethod(
        Invocation.getter(#isGenerating),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateDescription(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateDescription,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTotal(double? value) => super.noSuchMethod(
        Invocation.method(
          #updateTotal,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearItems() => super.noSuchMethod(
        Invocation.method(
          #clearItems,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateItemDescription(
    int? index,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateItemDescription,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateItemPrice(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateItemPrice,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateInvoiceNumber(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateInvoiceNumber,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDate(DateTime? value) => super.noSuchMethod(
        Invocation.method(
          #updateDate,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCurrency(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateCurrency,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void incrementInvoiceNumber() => super.noSuchMethod(
        Invocation.method(
          #incrementInvoiceNumber,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> saveDraft() => (super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void loadInvoice(_i7.Invoice? invoice) => super.noSuchMethod(
        Invocation.method(
          #loadInvoice,
          [invoice],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> deleteDraft(_i7.Invoice? draft) => (super.noSuchMethod(
        Invocation.method(
          #deleteDraft,
          [draft],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteHistoryEntry(_i7.Invoice? invoice) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHistoryEntry,
          [invoice],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllHistoryAndDrafts() => (super.noSuchMethod(
        Invocation.method(
          #clearAllHistoryAndDrafts,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> generateAndSaveInvoice() => (super.noSuchMethod(
        Invocation.method(
          #generateAndSaveInvoice,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateAndSaveInvoice,
            [],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
