name: MacOS Build & Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub global activate fastforge
          npm install -g appdmg

      - name: Generate App Icons
        run: dart run flutter_launcher_icons

      - name: Build MacOS App
        run: flutter build macos --release

      - name: Package DMG
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          fastforge release --name release

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Elada-MacOS-DMG
          path: dist/release/**/*.dmg
          if-no-files-found: error
